- name: Run node registry service
  hosts: server*
  remote_user: duongntd2
  tasks:
    - name: Install python libs
      ansible.builtin.pip:
        name:
          - docker
          - python-dotenv
          - requests
        state: latest

    - name: Copy node-registry directory
      ansible.builtin.copy:
        src: ../node-registry
        dest: /home/duongntd2

    - name: Run container
      shell:
        cmd: "bash run-container.sh"
        chdir: "/home/duongntd2/node-registry"
      register: output

    - name: Check container running
      ansible.builtin.debug:
        var: output.stderr_lines
  tags:
    - run-node-registry

- name: Stop node registry service
  hosts: server*
  remote_user: duongntd2
  tasks:
    - name: Stop container
      shell:
        cmd: "export NODE_IP=$(hostname -I | awk '{print $1}') HOSTNAME=$(hostname) && bash stop-container.sh"
        chdir: "/home/duongntd2/node-registry"
  tags:
    - stop-node-registry
