{
 "title": "Node Overview",
 "description": "OpenAdvices first published Dahsboard: Just one Table Widget to display the Certificate and Connection Status from HTTPS Connections that are Monitored with Prometheus.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Total Up Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_timex_sync_status{})"
    }
   ]
  },
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node Monitoring Table Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(node_memory_MemTotal_bytes{},  \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_FB_FREE{} + DCGM_FI_DEV_FB_USED{}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(sum((node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / node_memory_MemTotal_bytes{} * 100) by (instance), \"instance\", \"$1\", \"instance\", \"([^:]+).*\")",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "label_replace(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100), \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(((node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{}) / (node_memory_SwapTotal_bytes{} )) * 100, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node\"}) by (cpu))"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_FB_USED{} / (DCGM_FI_DEV_FB_USED{} + DCGM_FI_DEV_FB_FREE{}) * 100, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_UTIL{}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_POWER_USAGE{}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    },
    {
     "expr": "label_replace(node_time_seconds{} - node_boot_time_seconds{}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / node_memory_MemTotal_bytes{} * 100) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (hostname) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "SWAP Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{}) / (node_memory_SwapTotal_bytes{} )) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Usage % At \"/\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "VRAM Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{} / (DCGM_FI_DEV_FB_USED{} + DCGM_FI_DEV_FB_FREE{}) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "GPU utilization % ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL{}", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE{}", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}