{
 "title": "Triton Serving",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host: ",
    "query": {
     "query": "label_values(nv_inference_exec_count, host_gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Model Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of model executions performed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_exec_count{host_gpu=\"$node\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Number of inferences performed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_count{host_gpu=\"$node\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Number of successful inference requests, all batch sizes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_request_success{host_gpu=\"$node\"}"
    }
   ]
  },
  { "title": "Model Inference", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cummulative compute inference duration in microseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_duration_us{host_gpu=\"$node\"}"
    }
   ]
  },
  {
   "title": "Cummulative inference request duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us{host_gpu=\"$node\"}/1000000"
    }
   ]
  },
  {
   "title": "Cummulative compute input duration in microseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_compute_input_duration_us{host_gpu=\"$node\"}"
    }
   ]
  },
  {
   "title": "Cummulative inference compute output duration in miliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nv_inference_compute_output_duration_us{host_gpu=\"$node\"}/1000"
    }
   ]
  },
  {
   "title": "Cummulative inference queuing duration in microseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_queue_duration_us{host_gpu=\"$node\"}"
    }
   ]
  }
 ]
}